import React from 'react';

export const InterestBreakdown = ({ profile }) => {
  if (!profile || Object.keys(profile).length === 0) {
    return (
      <div
        className="editorial-card-muted"
        style={{ textAlign: 'center', padding: '2.5rem 1.5rem' }}
      >
        <p style={{ color: 'var(--text-secondary)' }}>
          Your technology profile is currently calculating. Add your explicit skills, sync your GitHub repos, or author technical posts to build your recommendation profile.
        </p>
      </div>
    );
  }

  const entries = Object.entries(profile).sort((a, b) => b[1] - a[1]);
  const maxScore = Math.max(...entries.map(([, score]) => score), 1);

  return (
    <div className="editorial-card animate-fade-in">
      <div style={{ marginBottom: '1.5rem' }}>
        <h3 style={{ fontSize: '1.2rem', marginBottom: '0.25rem' }}>
          Calculated Technology Affinity
        </h3>
        <p style={{ fontSize: '0.9rem', color: 'var(--text-secondary)' }}>
          Dynamic weights generated by the matching engine from your profile skills, projects, authored posts, and technical reactions.
        </p>
      </div>

      <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
        {entries.map(([tech, score]) => {
          const percentage = Math.round((score / maxScore) * 100);
          return (
            <div key={tech}>
              <div
                style={{
                  display: 'flex',
                  justifyContent: 'space-between',
                  alignItems: 'baseline',
                  marginBottom: '0.35rem',
                  fontFamily: 'var(--font-mono)',
                  fontSize: '0.85rem'
                }}
              >
                <span style={{ fontWeight: 600, color: 'var(--text-primary)' }}>{tech}</span>
                <span style={{ color: 'var(--accent)', fontWeight: 700 }}>
                  {score} pts ({percentage}%)
                </span>
              </div>
              <div
                style={{
                  height: '6px',
                  backgroundColor: 'var(--bg-secondary)',
                  borderRadius: 'var(--radius-full)',
                  overflow: 'hidden'
                }}
              >
                <div
                  style={{
                    height: '100%',
                    width: `${percentage}%`,
                    backgroundColor: 'var(--text-primary)',
                    borderRadius: 'var(--radius-full)',
                    transition: 'width 600ms cubic-bezier(0.16, 1, 0.3, 1)'
                  }}
                />
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
};

export default InterestBreakdown;
